services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - web